# Generated by Django 4.2.27 on 2025-12-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_contact_country_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the contact was created"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(
                help_text="Email address of the contact (must be unique)",
                max_length=254,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="event_notification_groups",
            field=models.TextField(
                blank=True,
                help_text="Groups to notify (required if event_notification_type is GROUPS)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="event_notification_type",
            field=models.CharField(
                choices=[("ALL_USERS", "All Users"), ("GROUPS", "Groups")],
                default="ALL_USERS",
                help_text="Type of notification: ALL_USERS or GROUPS",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="event_types",
            field=models.JSONField(
                help_text="List of event types that trigger notifications for this contact"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="first_name",
            field=models.CharField(
                help_text="First name of the contact (max 50 characters)", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="last_name",
            field=models.CharField(
                help_text="Last name of the contact (max 50 characters)", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="mobile_number",
            field=models.CharField(
                blank=True,
                help_text="Mobile phone number (optional, max 20 characters)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                default="ACTIVE",
                help_text="Current status of the contact: ACTIVE or INACTIVE",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the contact was last updated"
            ),
        ),
    ]
